production:
  cloud_name: "dmymbjgcm"
  api_key: "648991757278723"
  api_secret: "ty1HE9hz0WWf3VwkZtMtUNvSP1M"
  secure: true
  cdn_subdomain: true

development:
  cloud_name: "dmymbjgcm"
  api_key: "648991757278723"
  api_secret: "ty1HE9hz0WWf3VwkZtMtUNvSP1M"
  secure: true
  cdn_subdomain: true
